const radixColors = require('@radix-ui/colors');

// neutral - mauve
// primary - blue
// secondary - plum
// success - grass
// warning - amber
// error - crimson

module.exports = {
  neutral: {
    light: {
      1: radixColors.mauve.mauve1,
      2: radixColors.mauve.mauve2,
      3: radixColors.mauve.mauve3,
      4: radixColors.mauve.mauve4,
      5: radixColors.mauve.mauve5,
      6: radixColors.mauve.mauve6,
      7: radixColors.mauve.mauve7,
      8: radixColors.mauve.mauve8,
      9: radixColors.mauve.mauve9,
      10: radixColors.mauve.mauve10,
      11: radixColors.mauve.mauve11,
      12: radixColors.mauve.mauve12,
    },
    dark: {
      1: radixColors.mauveDark.mauve1,
      2: radixColors.mauveDark.mauve2,
      3: radixColors.mauveDark.mauve3,
      4: radixColors.mauveDark.mauve4,
      5: radixColors.mauveDark.mauve5,
      6: radixColors.mauveDark.mauve6,
      7: radixColors.mauveDark.mauve7,
      8: radixColors.mauveDark.mauve8,
      9: radixColors.mauveDark.mauve9,
      10: radixColors.mauveDark.mauve10,
      11: radixColors.mauveDark.mauve11,
      12: radixColors.mauveDark.mauve12,
    },
  },
  primary: {
    light: {
      1: radixColors.blue.blue1,
      2: radixColors.blue.blue2,
      3: radixColors.blue.blue3,
      4: radixColors.blue.blue4,
      5: radixColors.blue.blue5,
      6: radixColors.blue.blue6,
      7: radixColors.blue.blue7,
      8: radixColors.blue.blue8,
      9: radixColors.blue.blue9,
      10: radixColors.blue.blue10,
      11: radixColors.blue.blue11,
      12: radixColors.blue.blue12,
    },
    dark: {
      1: radixColors.blueDark.blue1,
      2: radixColors.blueDark.blue2,
      3: radixColors.blueDark.blue3,
      4: radixColors.blueDark.blue4,
      5: radixColors.blueDark.blue5,
      6: radixColors.blueDark.blue6,
      7: radixColors.blueDark.blue7,
      8: radixColors.blueDark.blue8,
      9: radixColors.blueDark.blue9,
      10: radixColors.blueDark.blue10,
      11: radixColors.blueDark.blue11,
      12: radixColors.blueDark.blue12,
    },
  },
  secondary: {
    light: {
      1: radixColors.plum.plum1,
      2: radixColors.plum.plum2,
      3: radixColors.plum.plum3,
      4: radixColors.plum.plum4,
      5: radixColors.plum.plum5,
      6: radixColors.plum.plum6,
      7: radixColors.plum.plum7,
      8: radixColors.plum.plum8,
      9: radixColors.plum.plum9,
      10: radixColors.plum.plum10,
      11: radixColors.plum.plum11,
      12: radixColors.plum.plum12,
    },
    dark: {
      1: radixColors.plumDark.plum1,
      2: radixColors.plumDark.plum2,
      3: radixColors.plumDark.plum3,
      4: radixColors.plumDark.plum4,
      5: radixColors.plumDark.plum5,
      6: radixColors.plumDark.plum6,
      7: radixColors.plumDark.plum7,
      8: radixColors.plumDark.plum8,
      9: radixColors.plumDark.plum9,
      10: radixColors.plumDark.plum10,
      11: radixColors.plumDark.plum11,
      12: radixColors.plumDark.plum12,
    },
  },
  success: {
    light: {
      1: radixColors.grass.grass1,
      2: radixColors.grass.grass2,
      3: radixColors.grass.grass3,
      4: radixColors.grass.grass4,
      5: radixColors.grass.grass5,
      6: radixColors.grass.grass6,
      7: radixColors.grass.grass7,
      8: radixColors.grass.grass8,
      9: radixColors.grass.grass9,
      10: radixColors.grass.grass10,
      11: radixColors.grass.grass11,
      12: radixColors.grass.grass12,
    },
    dark: {
      1: radixColors.grassDark.grass1,
      2: radixColors.grassDark.grass2,
      3: radixColors.grassDark.grass3,
      4: radixColors.grassDark.grass4,
      5: radixColors.grassDark.grass5,
      6: radixColors.grassDark.grass6,
      7: radixColors.grassDark.grass7,
      8: radixColors.grassDark.grass8,
      9: radixColors.grassDark.grass9,
      10: radixColors.grassDark.grass10,
      11: radixColors.grassDark.grass11,
      12: radixColors.grassDark.grass12,
    },
  },
  warning: {
    light: {
      1: radixColors.amber.amber1,
      2: radixColors.amber.amber2,
      3: radixColors.amber.amber3,
      4: radixColors.amber.amber4,
      5: radixColors.amber.amber5,
      6: radixColors.amber.amber6,
      7: radixColors.amber.amber7,
      8: radixColors.amber.amber8,
      9: radixColors.amber.amber9,
      10: radixColors.amber.amber10,
      11: radixColors.amber.amber11,
      12: radixColors.amber.amber12,
    },
    dark: {
      1: radixColors.amberDark.amber1,
      2: radixColors.amberDark.amber2,
      3: radixColors.amberDark.amber3,
      4: radixColors.amberDark.amber4,
      5: radixColors.amberDark.amber5,
      6: radixColors.amberDark.amber6,
      7: radixColors.amberDark.amber7,
      8: radixColors.amberDark.amber8,
      9: radixColors.amberDark.amber9,
      10: radixColors.amberDark.amber10,
      11: radixColors.amberDark.amber11,
      12: radixColors.amberDark.amber12,
    },
  },
  error: {
    light: {
      1: radixColors.crimson.crimson1,
      2: radixColors.crimson.crimson2,
      3: radixColors.crimson.crimson3,
      4: radixColors.crimson.crimson4,
      5: radixColors.crimson.crimson5,
      6: radixColors.crimson.crimson6,
      7: radixColors.crimson.crimson7,
      8: radixColors.crimson.crimson8,
      9: radixColors.crimson.crimson9,
      10: radixColors.crimson.crimson10,
      11: radixColors.crimson.crimson11,
      12: radixColors.crimson.crimson12,
    },
    dark: {
      1: radixColors.crimsonDark.crimson1,
      2: radixColors.crimsonDark.crimson2,
      3: radixColors.crimsonDark.crimson3,
      4: radixColors.crimsonDark.crimson4,
      5: radixColors.crimsonDark.crimson5,
      6: radixColors.crimsonDark.crimson6,
      7: radixColors.crimsonDark.crimson7,
      8: radixColors.crimsonDark.crimson8,
      9: radixColors.crimsonDark.crimson9,
      10: radixColors.crimsonDark.crimson10,
      11: radixColors.crimsonDark.crimson11,
      12: radixColors.crimsonDark.crimson12,
    },
  },
};
